### ISSUE TITLE
[Task] On app startup, immediately start reading tags

### ISSUE THREAD

**Issue by chusteven** [chusteven/BuildingAnNFCTagReaderApp#4]
Rather than this example repo doesn't do it until the user presses the "Scan" button

**Comment by midorinashi** [comment]
Ok I've totally failed to build this on my laptop, and now it is past midnight for me, but if you add `mainViewController?.beginScanning(0)` to right after `mainViewController?.addMessage(fromUserActivity: ndefMessage)` in AppDelegate this should work

The 0 doesn't matter, the function definition just needs something because it's being used in a button right now

I don't actually know how to remove the button because I've never used storyboards 🤔 But I think you can just delete the button??

**Comment by chusteven** [comment]
> Ok I've totally failed to build this on my laptop, and now it is past midnight for me, but if you add `mainViewController?.beginScanning(0)` to right after `mainViewController?.addMessage(fromUserActivity: ndefMessage)` in AppDelegate this should work
> 
> The 0 doesn't matter, the function definition just needs something because it's being used in a button right now
> 
> I don't actually know how to remove the button because I've never used storyboards 🤔 But I think you can just delete the button??

Tracey is that you?? In any case, this issue actually turns out isn't needed or even desired. I realized I needed a few more screens -- one to write data to tags, another to set IPs, ports, other configs for the HTTP requests, so... I actually _do_ want a button that specifically begins scanning and not just for the app to scan on its own :)
